### ISSUE TITLE
uninitialized constant Fluent::Input (NameError)

### ISSUE THREAD

**Issue by hc-chien** [winebarrel/fluent-plugin-zabbix-agent#2]
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-zabbix-agent-0.2.0/lib/fluent/plugin/in_zabbix_agent.rb:3:in `<top (required)>': uninitialized constant Fluent::Input (NameError)
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'

**Comment by cosmo0920** [comment]
Try #3.
